default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: fe_app_development


test:
  <<: *default
  database: fe_app_test
